
import { z } from "zod";

const questionTypes = ["multiple-choice", "true-false", "short-answer"] as const;
const difficultyLevels = ["easy", "medium", "hard"] as const;
const termOptions = ["First Term", "Second Term", "Third Term", "Others"] as const;
const classLevels = [
    "JSS1", "JSS2", "JSS3", "SS1", "SS2", "SS3", "WAEC", "NECO", "GCE WAEC", "GCE NECO"
] as const;

const insertQuestionSchema = z.object({
    questionText: z.string(),
    questionType: z.enum(questionTypes),
    subject: z.string(),
    difficulty: z.enum(difficultyLevels),
    options: z.array(z.string()).optional(),
    correctAnswer: z.string(),
    points: z.number().min(1).default(1),
    classLevel: z.enum(classLevels),
    term: z.enum(termOptions).default("First Term"),
    examType: z.string().default("Objectives"),
    imageUrl: z.string().optional(),
});

// This mimics the payload now generated by the fixed frontend code for Theory questions
const fixedPayload = {
    questionText: "Verified Theory Question",
    questionType: "multiple-choice",
    subject: "Math",
    difficulty: "medium",
    // options is explicitly undefined in the code, which means it might not be in the key-values 
    // or it's explicitly set to undefined. 
    // In JS, { options: undefined } is often treated same as missing by JSON.stringify but Zod handles it.
    options: undefined,
    correctAnswer: "Theory Question",
    classLevel: "JSS1",
    term: "First Term",
    examType: "Theory"
};

const result = insertQuestionSchema.safeParse(fixedPayload);

if (result.success) {
    console.log("VERIFICATION PASSED: Payload with options: undefined is valid.");
} else {
    console.error("VERIFICATION FAILED:", JSON.stringify(result.error.errors, null, 2));
    process.exit(1);
}
